config/routes.rb
Ideasweb::Application.routes.draw do
  resources :foros

  devise_for :users

  resources :ideas do
    resources :comments
    member do
      post 'vote_up'
      post 'vote_down'
    end
  end
  resources :foros do
    resources :comments
    end

  root :to => "ideas#index"

  
 

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
  
end

app/models/foro.rb
class Foro < ActiveRecord::Base
  acts_as_commentable
  belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  acts_as_commentable  
  acts_as_votable
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :ideas
  has_many :foros
  
  acts_as_voter
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    
    @comment = Comment.new(params[:comment])
    @commentable = find_commentable
    @comment.commentable = @commentable
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: 'Comment was successfully created.' }
        format.json { render json: @commentable, status: :created, location: @commentable }
      else
        format.html { render action: @commentable }
        format.json { render json: @commentable.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

def find_commentable
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil
end
  
 
end

app/controllers/foros_controller.rb
class ForosController < ApplicationController
  before_filter :authenticate_user!
  
  
  # GET /foros
  # GET /foros.json
  def index
    @foros = Foro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foros }
    end
  end

  # GET /foros/1
  # GET /foros/1.json
  def show
    @foro = Foro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foro }
    end
  end

  # GET /foros/new
  # GET /foros/new.json
  def new
    @foro = Foro.new
    @comment = Comment.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foro }
    end
  end

  # GET /foros/1/edit
  def edit
    @foro = Foro.find(params[:id])
  end

  # POST /foros
  # POST /foros.json
  def create
    @foro = Foro.new(params[:foro])
    @foro.user = current_user
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @foro.comments << @comment

    respond_to do |format|
      if @foro.save
        format.html { redirect_to @foro, notice: 'Foro was successfully created.' }
        format.json { render json: @foro, status: :created, location: @foro }
      else
        format.html { render action: "new" }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foros/1
  # PUT /foros/1.json
  def update
    @foro = Foro.find(params[:id])

    respond_to do |format|
      if @foro.update_attributes(params[:foro])
        format.html { redirect_to @foro, notice: 'Foro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foros/1
  # DELETE /foros/1.json
  def destroy
    @foro = Foro.find(params[:id])
    @foro.destroy

    respond_to do |format|
      format.html { redirect_to foros_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, :except => :index
  
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
    if @idea.user != current_user
      flash[:notice] = "No puedes modificar ideas de otros"
      redirect_to idea_url(@idea)
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    @idea.user = current_user
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])
    if @idea.user != current_user
      flash[:notice] = "No puedes modificar ideas de otros"
      redirect_to idea_url(@idea)
    end
    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    if @idea.user != current_user
      flash[:notice] = "No puedes modificar ideas de otros"
      redirect_to idea_url(@idea)
    end
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
  
  def vote_up
    @idea = Idea.find(params[:id])
    @idea.liked_by current_user
    flash[:notice] = "Tu voto ha sido registrado"
    redirect_to idea_url(@idea)
  end
  
  def vote_down
    @idea = Idea.find(params[:id])
    @idea.downvote_from current_user
    flash[:notice] = "Tu voto ha sido registrado"
    redirect_to idea_url(@idea)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/foros_helper.rb
module ForosHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_comment_form.html.erb
<div class="comment">
  <%= form_for [commentable, Comment.new] do |f| %>
  <p>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit "Submit"  %>
  </p>
  
<% end %>
</div>

app/views/comments/_comments.html.erb
  <% for comment in commentable.comments %>
    <tr><th><%= comment.user.email %></th><th><%= comment.created_at.to_formatted_s(:short)  %></th></tr>
    <tr><td colspan='2'><%= comment.comment %></td></tr>
  <% end %>

app/views/foros/.#index.html.erb
alago@linux-n27o.site.6968:1333008016

app/views/foros/_form.html.erb
<%= form_for(@foro) do |f| %>
  <% if @foro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foro.errors.count, "error") %> prohibited this foro from being saved:</h2>

      <ul>
      <% @foro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>  
    <div class="comment">
  <%= fields_for @comment do |c| %>
    
    <%= c.text_area :comment %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foros/edit.html.erb
<h1>Editing foro</h1>

<%= render 'form' %>

<%= link_to 'Show', @foro %> |
<%= link_to 'Back', foros_path %>

app/views/foros/index.html.erb
<table>
  <tr>
    <th>Titulo</th>
    <th>Creador</th>
    <th>Fecha</th>
   
  </tr>

<% @foros.each do |foro| %>
  <tr>
    <td><%= link_to foro.titulo, foro %></td>
    <td><%= foro.user.email %></td>
    <td><%= foro.created_at %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Hilo', new_foro_path %>

app/views/foros/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', foros_path %>

app/views/foros/show.html.erb
<table class="comments_table">


  <tr><th colspan='2' class='titulo_foro'><b><%= @foro.titulo %></b></th></tr>
  <%= render :partial => "comments/comments", :locals => { :commentable => @foro } %>
</table>
<%= render :partial => "comments/comment_form", :locals => { :commentable => @foro } %>

<%= link_to 'Edit', edit_foro_path(@foro) %> |
<%= link_to 'Back', foros_path %> |
<%= link_to 'Destroy', @foro, confirm: 'Are you sure?', method: :delete %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="Sentence 1">
    <h2>Sentence 1</h1>
    <%= f.label 'For' %>
    <%= f.text_field :target %>
    
    <%= f.label 'who' %>
    <%= f.text_field :need_statement %>
   <br/>
    <%= f.label 'The' %>
    <%= f.text_field :product_name %>
 
    <%= f.label 'is a' %>
    <%= f.text_field :product_cat %>
    <br/>
    <%= f.label 'that' %>
    <%= f.text_field :benefit_statement %>
  </div>
  <div class="Sentence 2">
    <h2>Sentence 2</h1>
    <%= f.label 'Unlike' %>
    <%= f.text_field :alternative %>
    <br/>
    <%= f.label 'Our product' %>
    <%= f.text_field :differentiation %>
  </div>
<br/>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<!--<h1>Listing ideas</h1> -->

<table>
  <tr>
    <th>Target</th>
    <th>Creador</th>
    <th>Creado</th>
    <th>Votos a favor</th>
    <th>Votos en contra</th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= link_to idea.target, idea %></td>
    <td><%= idea.user.email %></td>
    <td><%= idea.created_at.to_formatted_s(:short) %></td>
    <td><%= idea.likes.size %></td>
    <td><%= idea.dislikes.size %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<div Sentence 1>
  <h1 id="sentence">Sentence 1</h1>
  <b>For </b> <%= @idea.target %> <b>who</b> <%= @idea.need_statement %><br/>
  <b>The</b> <%= @idea.product_name %> <b> is a</b> <%= @idea.product_cat %><br/>
  <b>That</b>  <%= @idea.benefit_statement %> <br/>
</div>
<div Sentence 2>
  <h1 id="sentence">Sentence 2</h1>
  <b>Unlike </b> <%= @idea.alternative %> <br/>
  <b>Our Product</b>  <%= @idea.differentiation %> <br/>
</div>

<div class="votos">
 <%= link_to "+1", vote_up_idea_url(@idea), :method => :post
 -%>&nbsp;|&nbsp;<%= link_to "-1", vote_down_idea_url(@idea), :method => :post -%>
</div>

<%= render :partial => "comments/comment_form", :locals => { :commentable => @idea } %>
<table class="comments_table">
<%= render :partial => "comments/comments", :locals => { :commentable => @idea } %>
</table>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %> |
<%= link_to 'Destroy', @idea, confirm: 'Are you sure?', method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideasweb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="banner">
  <span id="links">
  <%= link_to 'Inicio', root_url() %> &nbsp;|&nbsp;
  <%= link_to 'Foro', foros_url() %>
  </span>
  <span id="login">
  <% if current_user -%>
    Hola <%= current_user.email %>&nbsp;|&nbsp;
    <%= link_to "Log Out", destroy_user_session_path(), :method => :delete -%>
  <% else -%>
    Regístrate!&nbsp;|&nbsp;<%= link_to "Log In", new_user_session_path() -%>&nbsp;|&nbsp;<%= link_to "Sign Up", new_user_registration_path() -%>
  <% end -%>
  </span>
  </div>
<br/>
<hr/>
<br/>
  <div id="container">
    <p id="notice"><%= notice %></p>


    <%= yield %>

  </div>
</body>
</html>